# Generated by Django 4.2.24 on 2025-09-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='إيمان يوسف النجار', max_length=255)),
                ('title', models.CharField(default='محامية شرعية', max_length=255)),
                ('description', models.TextField(default='خبيرة في تقديم الاستشارات القانونية والقضايا الشرعية.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='homepage/')),
                ('consultation_url', models.URLField(default='/consultation/')),
            ],
        ),
    ]
