# Generated by Django 4.2.24 on 2025-09-19 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_newsletter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
