"""Create SiteStats model

Generated by assistant as a manual migration to add SiteStats model.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cases_won', models.PositiveIntegerField(default=152)),
                ('years_experience', models.PositiveIntegerField(default=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Stats',
                'verbose_name_plural': 'Site Stats',
            },
        ),
    ]
"""Placeholder migration 0004_sitestats

No-op migration placeholder to satisfy the migration graph after previous edits.
If you want to add SiteStats models, create a proper migration using makemigrations.
"""
from django.db import migrations


class Migration(migrations.Migration):
	dependencies = [
		('core', '0003_newsletter'),
	]

	operations = [
	]
