# Generated by Django 4.2.24 on 2025-09-19 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_homepage'),
        ('core', '0004_sitestats'),
    ]

    operations = [
    ]
