# Generated by Django 4.2.24 on 2025-09-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_0004_delete_homepage_0004_sitestats'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cases_won', models.PositiveIntegerField(default=152)),
                ('years_experience', models.PositiveIntegerField(default=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Stats',
                'verbose_name_plural': 'Site Stats',
            },
        ),
    ]
