# Generated by Django 4.2.24 on 2025-09-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitestats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitestats',
            name='years_experience',
        ),
        migrations.AlterField(
            model_name='sitestats',
            name='cases_won',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
