# Generated by Django 4.2.24 on 2025-09-20 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='case_type',
            field=models.CharField(blank=True, help_text='نوع القضية', max_length=120),
        ),
        migrations.AddField(
            model_name='case',
            name='client_initials',
            field=models.CharField(blank=True, help_text='مثال: أ.س', max_length=10),
        ),
        migrations.AddField(
            model_name='case',
            name='outcome',
            field=models.CharField(blank=True, help_text='النتيجة', max_length=120),
        ),
        migrations.CreateModel(
            name='CaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='case_docs/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.case')),
            ],
        ),
    ]
