# Generated by Django 4.2.24 on 2025-09-20 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_case_case_date_case_case_type_case_client_initials_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'فئة',
                'verbose_name_plural': 'فئات',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'وسم',
                'verbose_name_plural': 'وسوم',
            },
        ),
        migrations.CreateModel(
            name='CaseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='case_images/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.case')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='core.category'),
        ),
        migrations.AddField(
            model_name='case',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='cases', to='core.tag'),
        ),
    ]
