# Generated by Django 4.2.24 on 2025-09-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_category_tag_caseimage_case_category_case_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
