# Generated by Django 4.2.24 on 2025-09-17 09:05

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_og_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='processed_og_image',
            field=models.ImageField(blank=True, editable=False, help_text='صورة معالجة بالحجم الأمثل للـ OG (تُولد تلقائيًا)', null=True, upload_to='og_images/processed/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='og_image',
            field=models.ImageField(blank=True, help_text='يفضل 1200x630px، صيغ JPG أو PNG، وحجم لا يتجاوز 5 ميغابايت', null=True, upload_to='og_images/', validators=[core.validators.validate_og_image]),
        ),
    ]
