# Generated by Django 4.2.24 on 2025-09-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_processed_og_image_alter_blogpost_og_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='processed_og_image',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='processed_og_image_large',
            field=models.ImageField(blank=True, editable=False, help_text='صورة معالجة بالحجم 1200x630px (تُولد تلقائيًا)', null=True, upload_to='og_images/processed/large/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='processed_og_image_medium',
            field=models.ImageField(blank=True, editable=False, help_text='صورة معالجة بالحجم 800x420px (تُولد تلقائيًا)', null=True, upload_to='og_images/processed/medium/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='processed_og_image_small',
            field=models.ImageField(blank=True, editable=False, help_text='صورة معالجة بالحجم 400x210px (تُولد تلقائيًا)', null=True, upload_to='og_images/processed/small/'),
        ),
    ]
