# Generated by Django 4.2.24 on 2025-09-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_notificationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, help_text='مصغرة صغيرة لاستخدامها في نتائج البحث والقوائم', null=True, upload_to='blog_images/thumbnails/'),
        ),
    ]
